// Scripted UDS flash sessions rendered as CAN frames, plus writers for each trace format.
// Shared by scripts/make-fixtures.mjs and the tests.
export const TESTER = 0x7e0;
export const ECU = 0x7e8;
export const VIN = "W0L000043MB541326";
export const BLOCK = 256;

export function imageBytes(size = 4 * BLOCK) {
  return Array.from({ length: size }, (_, i) => (i * 7 + 3) & 0xff);
}

function builder() {
  let t = 0;
  const frames = [];
  const push = (id, data) => frames.push({ t, id, data: [...data, ...Array(8 - data.length).fill(0xaa)] });
  // ISO-TP send: SF, or FF + FC from the receiver + CFs, 1 ms apart
  const send = (from, to, payload) => {
    if (payload.length <= 7) {
      push(from, [payload.length, ...payload]);
      t += 1;
      return;
    }
    push(from, [0x10 | (payload.length >> 8), payload.length & 0xff, ...payload.slice(0, 6)]);
    t += 1;
    push(to, [0x30, 0x00, 0x00]);
    t += 1;
    let sn = 1;
    for (let o = 6; o < payload.length; o += 7) {
      push(from, [0x20 | sn, ...payload.slice(o, o + 7)]);
      sn = (sn + 1) & 0xf;
      t += 1;
    }
  };
  const req = (p) => send(TESTER, ECU, p);
  const rsp = (p) => send(ECU, TESTER, p);
  const wait = (ms) => (t += ms);
  return { frames, req, rsp, wait };
}

const ascii = (s) => [...s].map((c) => c.charCodeAt(0));

function prologue(b) {
  b.req([0x10, 0x03]); b.wait(5); b.rsp([0x50, 0x03, 0x00, 0x32, 0x01, 0xf4]); b.wait(20);
  b.req([0x22, 0xf1, 0x90]); b.wait(5); b.rsp([0x62, 0xf1, 0x90, ...ascii(VIN)]); b.wait(20);
  b.req([0x85, 0x02]); b.wait(5); b.rsp([0xc5, 0x02]); b.wait(20);
  b.req([0x28, 0x03, 0x01]); b.wait(5); b.rsp([0x68, 0x03]); b.wait(20);
  b.req([0x10, 0x02]); b.wait(5); b.rsp([0x50, 0x02, 0x00, 0x32, 0x01, 0xf4]); b.wait(50);
  b.req([0x27, 0x01]); b.wait(5); b.rsp([0x67, 0x01, 0x11, 0x22, 0x33, 0x44]); b.wait(20);
  b.req([0x27, 0x02, 0xaa, 0xbb, 0xcc, 0xdd]); b.wait(5); b.rsp([0x7f, 0x27, 0x35]); b.wait(100);
  b.req([0x27, 0x01]); b.wait(5); b.rsp([0x67, 0x01, 0x55, 0x66, 0x77, 0x88]); b.wait(20);
  b.req([0x27, 0x02, 0x9a, 0x98, 0x88, 0x77]); b.wait(5); b.rsp([0x67, 0x02]); b.wait(20);
  b.req([0x3e, 0x80]); b.wait(20);
  b.req([0x31, 0x01, 0xff, 0x00]); b.wait(10); b.rsp([0x7f, 0x31, 0x78]); b.wait(800); b.rsp([0x71, 0x01, 0xff, 0x00]); b.wait(20);
  b.req([0x34, 0x00, 0x44, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00]); b.wait(5); b.rsp([0x74, 0x20, 0x01, 0x02]); b.wait(10);
}

const block = (img, n) => [0x36, n, ...img.slice((n - 1) * BLOCK, n * BLOCK)];

/** Successful flash: block 3 is sent twice (first try unanswered). */
export function flashOk() {
  const b = builder();
  const img = imageBytes();
  prologue(b);
  b.req(block(img, 1)); b.wait(5); b.rsp([0x76, 0x01]); b.wait(5);
  b.req(block(img, 2)); b.wait(5); b.rsp([0x76, 0x02]); b.wait(5);
  b.req(block(img, 3)); b.wait(200);
  b.req(block(img, 3)); b.wait(5); b.rsp([0x76, 0x03]); b.wait(5);
  b.req(block(img, 4)); b.wait(5); b.rsp([0x76, 0x04]); b.wait(10);
  b.req([0x37]); b.wait(5); b.rsp([0x77]); b.wait(10);
  b.req([0x31, 0x01, 0xff, 0x01]); b.wait(5); b.rsp([0x71, 0x01, 0xff, 0x01, 0x00]); b.wait(10);
  b.req([0x11, 0x01]); b.wait(5); b.rsp([0x51, 0x01]); b.wait(5);
  return b.frames;
}

/** Failed flash: block 3 skipped -> 7F 36 73, then the ECU stops answering after a new erase request. */
export function flashFail() {
  const b = builder();
  const img = imageBytes();
  prologue(b);
  b.req(block(img, 1)); b.wait(5); b.rsp([0x76, 0x01]); b.wait(5);
  b.req(block(img, 2)); b.wait(5); b.rsp([0x76, 0x02]); b.wait(5);
  b.req(block(img, 4)); b.wait(5); b.rsp([0x7f, 0x36, 0x73]); b.wait(50);
  b.req([0x31, 0x01, 0xff, 0x00]); b.wait(6000);
  b.req([0x3e, 0x80]); b.wait(1);
  return b.frames;
}

const H = (b) => b.toString(16).toUpperCase().padStart(2, "0");
const id3 = (id) => id.toString(16).toUpperCase().padStart(3, "0");
const BASE = 1696412345; // epoch seconds for absolute-time formats
const dir = (id) => (id === TESTER ? "Tx" : "Rx");

export const writers = {
  candump: (fr) => fr.map((f) => `(${(BASE + f.t / 1000).toFixed(6)}) can0 ${id3(f.id)}#${f.data.map(H).join("")}`).join("\n") + "\n",
  asc: (fr) =>
    ["date Wed Oct 4 10:00:00.000 am 2026", "base hex  timestamps absolute", "internal events logged", "// version 9.0.0", "Begin Triggerblock Wed Oct 4 10:00:00.000 am 2026", "   0.000000 Start of measurement",
      ...fr.map((f) => `   ${(f.t / 1000).toFixed(6)} 1  ${id3(f.id)}             ${dir(f.id)}   d 8 ${f.data.map(H).join(" ")}  Length = 240000 BitCount = 124 ID = ${f.id}`), "End TriggerBlock"].join("\n") + "\n",
  trc21: (fr) =>
    [";$FILEVERSION=2.1", ";$STARTTIME=45203.4166666667", ";$COLUMNS=N,O,T,B,I,d,R,L,D", ";", ";   Generated by test scenario",
      ...fr.map((f, i) => `${String(i + 1).padStart(7)} ${f.t.toFixed(3).padStart(13)} DT 1      ${f.id.toString(16).toUpperCase().padStart(4, "0")} ${dir(f.id)} -  8    ${f.data.map(H).join(" ")}`)].join("\n") + "\n",
  trc11: (fr) =>
    [";$FILEVERSION=1.1", ";$STARTTIME=45203.4166666667", ";   Message Number", ";   |         Time Offset (ms)",
      ...fr.map((f, i) => `${String(i + 1).padStart(6)})  ${f.t.toFixed(1).padStart(11)}  ${dir(f.id)}         ${f.id.toString(16).toUpperCase().padStart(4, "0")}  8  ${f.data.map(H).join(" ")}`)].join("\n") + "\n",
  savvycan: (fr) =>
    ["Time Stamp,ID,Extended,Dir,Bus,LEN,D1,D2,D3,D4,D5,D6,D7,D8",
      ...fr.map((f) => `${Math.round(f.t * 1000)},${f.id.toString(16).toUpperCase().padStart(8, "0")},false,${dir(f.id)},0,8,${f.data.map(H).join(",")}`)].join("\n") + "\n",
  pythoncan: (fr) =>
    ["timestamp,arbitration_id,extended,remote,error,dlc,data",
      ...fr.map((f) => `${(BASE + f.t / 1000).toFixed(6)},0x${f.id.toString(16).toUpperCase()},0,0,0,8,${btoa(String.fromCharCode(...f.data))}`)].join("\n") + "\n",
};
