// Bundles the trace viewer: (a) a self-contained widget HTML string for the MCP resource,
// (b) viewer/app.js + viewer/app.css for udslib.com/viewer.html.
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const here = (p) => new URL(p, import.meta.url);
const css = readFileSync(here("../viewer/viewer.css"), "utf8");
const common = { bundle: true, format: "esm", target: "es2020", minify: true, legalComments: "none", write: false, charset: "utf8" };

const widget = await build({ ...common, entryPoints: [here("../viewer/widget-entry.mjs").pathname] });
const widgetJs = widget.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UDS trace viewer</title><style>html,body{margin:0;background:transparent}#root{padding:12px}${css}</style></head><body><div id="root"></div><script type="module">/* renderAnalysis */${widgetJs}</script></body></html>`;
mkdirSync(here("../src/generated/"), { recursive: true });
writeFileSync(here("../src/generated/widget-html.mjs"), `// Generated by scripts/build-viewer.mjs. Do not edit.\nexport default ${JSON.stringify(html)};\n`);

const page = await build({ ...common, entryPoints: [here("../viewer/page-entry.mjs").pathname] });
mkdirSync(here("../../viewer/"), { recursive: true });
writeFileSync(here("../../viewer/app.js"), page.outputFiles[0].text);
writeFileSync(here("../../viewer/app.css"), css);
console.log(`widget ${(html.length / 1024).toFixed(1)} KiB, page bundle ${(page.outputFiles[0].text.length / 1024).toFixed(1)} KiB`);
